apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: web
  namespace: website
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: pojntfx/libresat-website
          ports:
            - containerPort: 2015
