apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opensdcp-wiki-web-images
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi