apiVersion: v1
kind: Service
metadata:
  name: opensdcp-forum-web
spec:
  selector:
    app: opensdcp-forum-web
    tier: backend
    track: stable
  ports:
    - name: web
      targetPort: web
      port: 3000
  type: NodePort