apiVersion: v1
kind: Service
metadata:
  name: opensdcp-git-db
spec:
  selector:
    app: opensdcp-git-db
    tier: backend
    track: stable
  ports:
    - name: db
      targetPort: db
      port: 5432
  type: NodePort