apiVersion: v1
kind: Service
metadata:
  name: opensdcp-git-web
spec:
  selector:
    app: opensdcp-git-web
    tier: backend
    track: stable
  ports:
    - name: web
      targetPort: web
      port: 2000
    - name: ssh
      targetPort: ssh
      port: 2001
  type: NodePort