{{- $relname := .Release.Name }}
{{- $s3accessKey := .Values.s3.accessKey }}
{{- $s3secretAccessKey := .Values.s3.secretAccessKey }}

{{- range .Values.targets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $relname }}-{{ .name }}
  namespace: {{ .namespace }}
stringData:
  AWS_ACCESS_KEY_ID: {{ $s3accessKey }}
  AWS_SECRET_ACCESS_KEY: {{ $s3secretAccessKey }}
  RESTIC_PASSWORD: {{ .password }}
{{ end }}