apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web
  namespace: webmail
spec:
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - path: /
            backend:
              serviceName: web
              servicePort: web