apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: wiki
spec:
  ports:
    - name: web
      port: 80
      targetPort: 5001
    - name: ssh
      port: 22
      targetPort: 22
  selector:
    app: web