apiVersion: v1
kind: PersistentVolume
metadata:
  name: opensdcp-forum-db
spec:
  capacity:
    storage: 10Gi
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /data/opensdcp-forum-db-data