apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web
  namespace: {{ .Release.Namespace }}
spec:
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - path: /forum
            backend:
              serviceName: web
              servicePort: web
          - path: /static
            backend:
              serviceName: web
              servicePort: web
