apiVersion: v1
kind: PersistentVolume
metadata:
  name: opensdcp-git-db
spec:
  capacity:
    storage: 10Gi
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /data/opensdcp-git-db-data