apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: opensdcp-wiki-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: opensdcp-wiki-db
        tier: backend
        track: stable
    spec:
      containers:
        - image: pastakhov/mysql:5.7
          name: db
          ports:
            - name: db
              containerPort: 3306
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/mysql
          env:
            - name: MYSQL_ROOT_HOST
              value: "%"
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: opensdcp-wiki-config
                  key: db_root_password
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: opensdcp-wiki-db