apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: opensdcp-wiki-memcached
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: opensdcp-wiki-memcached
        tier: backend
        track: stable
    spec:
      containers:
        - image: memcached
          name: memcached
          ports:
            - name: memcached
              containerPort: 11211