apiVersion: v1
kind: PersistentVolume
metadata:
  name: opensdcp-wiki-web-images
spec:
  capacity:
    storage: 10Gi
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /data/opensdcp-wiki-web-images-data