apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: opensdcp-git-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: opensdcp-git-db
        tier: backend
        track: stable
    spec:
      containers:
        - image: postgres:9.6
          name: db
          ports:
            - name: db
              containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: opensdcp-git-config
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: opensdcp-git-config
                  key: postgres_password
            - name: POSTGRES_DB
              value: gitea
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: opensdcp-git-db