apiVersion: v1
kind: Service
metadata:
  name: opensdcp-wiki-elasticsearch
spec:
  selector:
    app: opensdcp-wiki-elasticsearch
    tier: backend
    track: stable
  ports:
    - name: elasticsearch
      targetPort: elasticsearch
      port: 9200
  type: NodePort