apiVersion: v1
kind: Service
metadata:
  name: opensdcp-wiki-parsoid
spec:
  selector:
    app: opensdcp-wiki-parsoid
    tier: backend
    track: stable
  ports:
    - name: parsoid
      targetPort: parsoid
      port: 8000
  type: NodePort