apiVersion: v1
kind: Service
metadata:
  name: opensdcp-wiki-restbase
spec:
  selector:
    app: opensdcp-wiki-restbase
    tier: backend
    track: stable
  ports:
    - name: restbase
      targetPort: restbase
      port: 7231
  type: NodePort