# RainLoop on Kubernetes
# See: https://github.com/hardware/rainloop
# Initial Credentials (change them after you've logged in):
# URL: https://webmail.stg1.libresat.space/?admin (don't forget the ?admin!)
# User: admin
# Password: 12345
# See https://github.com/hardware/mailserver/wiki/Rainloop-initial-configuration for more details
apiVersion: v1
kind: Namespace
metadata:
  name: rainloop
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: web
  namespace: rainloop
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: hardware/rainloop
          ports:
            - containerPort: 8888
          volumeMounts:
            - name: data
              mountPath: "/rainloop/data"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: rainloop
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: rainloop
spec:
  ports:
    - name: web
      port: 80
      targetPort: 8888
  selector:
    app: web
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web
  namespace: rainloop
spec:
  rules:
    - host: webmail.stg1.libresat.space
      http:
        paths:
          - path: /
            backend:
              serviceName: web
              servicePort: web
