version: "3"

services: 
  web:
    image: mondedie/docker-flarum:0.1.0-beta.7.1-stable
    ports:
      - "3100:8888"
    environment:
      - FORUM_URL=${FORUM_URL}
      - DB_PASS=${DB_PASSWORD}
    networks:
      - opensdcp-forum
    volumes:
      - ./opensdcp-forum-web-assets-data-dev:/flarum/app/assets
      - ./opensdcp-forum-web-extensions-data-dev:/flarum/app/extensions
    depends_on:
      - db
  db:
    image: mariadb:10.1
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=flarum
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      - opensdcp-forum
    volumes:
      - ./opensdcp-forum-db-data-dev:/var/lib/mysql

networks: 
  opensdcp-forum:
